{% set name = "veusz" %}
{% set version = "3.1" %}
{% set sha256 = "c2e2c1bd6891c21fc05484f3b87db52274378e9bf8d4cfa44ea689e56b22f77e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

extra:
  container:
    extended-base: true

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - qt
    - sip
    - pyqt
    - numpy
  run:
    - python
    - qt
    - pyqt
    - {{ pin_compatible('numpy') }}
    - setuptools

test:
  imports:
    - veusz
  commands:
    - veusz -platform minimal --help

app:
  entry: veusz
  icon: veusz_64.png
  summary: "Veusz 2D and 3D interactive scientific plotting"
  type: desk

about:
  home: https://veusz.github.io/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: '2D and 3D interactive scientific plotting GUI and module'

  description: |
    Veusz is a 2D and 3D scientific plotting package, designed to
    create publication-ready PDF and SVG output. It features GUI,
    command-line, and scripting interfaces. Graphs are constructed
    from widgets, allowing complex layouts to be designed. Veusz
    supports plotting functions, data with errors, keys, labels,
    stacked plots, multiple plots, and fitting data.
  doc_url: https://veusz.github.io/help-support/
  dev_url: https://veusz.github.io/development/

extra:
  recipe-maintainers:
    - jeremysanders
